# Generated by Django 5.2.1 on 2025-06-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_item_image_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_branch',
            field=models.CharField(blank=True, choices=[('atlas1', 'Atlas Burger 1 - Main Branch'), ('atlas2', 'Atlas Burger 2 - Downtown')], max_length=20, null=True),
        ),
    ]
